name: Build Docker images


on:

  push:
    branches: 
      - "master"

  schedule:
    - cron: "0 0 * * 4"

  workflow_dispatch:


jobs:

  build_and_publish_81:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "master"

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: eworkssk/php-fpm
          tags: 8.1, 8, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
